version: '3.8'
services:
  captain_frontend:
    restart: always
    build: .
    image: node:14.16.0-alpine
    command: sh -c "npm install && npm run build &&
      npm start"
    ports:
      - 3030:3030
    working_dir: /app
    volumes:
      - ./:/app
